name: CI

on:
#   push:
#     paths:
#       - 'release-versions/*'
   workflow_dispatch:


jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

       - name: Install Java
         uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
           java-version: '17'

       - name: Update the system
         run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt install curl grep

       - name: Build youtube
         env:
            KEYSTORE: ${{ secrets.YOUTUBE_KEYSTORE }}
         run: |
          # curl -OL https://github.com/SubhashBose/revanced-creator/releases/download/keystores/revanced-creator.keystore
          echo "$KEYSTORE" | base64 --decode > revanced-creator.keystore
          export additional_args="--keystore=revanced-creator.keystore"
          sh -c "$(curl https://raw.githubusercontent.com/SubhashBose/revanced-creator/main/patch.sh)"
          curl -OL https://github.com/SubhashBose/revanced-creator/releases/download/youtube/vanced-microg.apk

       - name: Upload Build Artifact(youtube)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-youtube
           path: |
            revanced-*-non-root.apk
            vanced-microg.apk

       - name: Build youtube-music
         env:
            KEYSTORE: ${{ secrets.YTMUSIC_KEYSTORE }}
         run: |
          # curl -OL https://github.com/SubhashBose/revanced-creator/releases/download/keystores/revanced-creator-music.keystore
          echo "$KEYSTORE" | base64 --decode > revanced-creator-music.keystore
          export additional_args="--keystore=revanced-creator-music.keystore"
          export what_to_patch="youtube-music"
          sh -c "$(curl https://raw.githubusercontent.com/SubhashBose/revanced-creator/main/patch.sh)"

       - name: Upload Build Artifact(YouTube-Music)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-music
           path: revanced-music-*-non-root.apk

       - name: Build twitch
         run: |
          export what_to_patch="twitch"
          sh -c "$(curl https://raw.githubusercontent.com/SubhashBose/revanced-creator/main/patch.sh)"

       - name: Upload Build Artifact(Twitch)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-twitch
           path: revanced-twitch-*-non-root.apk

       - name: Build reddit
         run: |
          # curl -OL https://github.com/SubhashBose/revanced-creator/releases/download/keystores/revanced-creator-reddit.keystore
          # export additional_args="--keystore=revanced-creator-reddit.keystore"
          export what_to_patch="reddit"
          sh -c "$(curl https://raw.githubusercontent.com/SubhashBose/revanced-creator/main/patch.sh)"

       - name: Upload Build Artifact(Reddit)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-reddit
           path: revanced-reddit-*-non-root.apk

       - name: Build twitter
         run: |
          # curl -OL https://github.com/SubhashBose/revanced-creator/releases/download/keystores/revanced-creator-twitter.keystore
          # export additional_args="--keystore=revanced-creator-twitter.keystore"
          export what_to_patch="twitter"
          sh -c "$(curl https://raw.githubusercontent.com/SubhashBose/revanced-creator/main/patch.sh)"

       - name: Upload Build Artifact(Twitter)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-twitter
           path: revanced-twitter-*-non-root.apk

       - name: Build tiktok
         run: |
          export what_to_patch="tiktok"
          sh -c "$(curl https://raw.githubusercontent.com/SubhashBose/revanced-creator/main/patch.sh)"

       - name: Upload Build Artifact(TikTok)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-tiktok
           path: revanced-tiktok-*-non-root.apk

       - name: Build spotify
         run: |
          export what_to_patch="spotify"
          sh -c "$(curl https://raw.githubusercontent.com/SubhashBose/revanced-creator/main/patch.sh)"

       - name: Upload Build Artifact(Spotify)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-spotify
           path: revanced-spotify-*-non-root.apk
