name: CI

on:
#   push:
#     paths:
#       - 'release-versions/*'
   workflow_dispatch:


jobs:
   build-youtube:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

       - name: Install Java
         uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
           java-version: '17'

       - name: Update the system
         run: sudo apt install curl ripgrep

       - name: Build youtube
         env:
            KEYSTORE: ${{ secrets.KEYSTORE }}
         run: |
          # curl -OL https://github.com/SubhashBose/revanced-creator/releases/download/keystores/revanced-creator.keystore
          echo "$KEYSTORE" | base64 --decode > revanced-creator.keystore
          export additional_args="--keystore=revanced-creator.keystore"
          sh -c "$(curl https://raw.githubusercontent.com/SubhashBose/revanced-creator/main/patch.sh)"
          #cat revanced-youtube*.keystore |base64
          curl -OL https://github.com/SubhashBose/revanced-creator/releases/download/youtube/vanced-microg.apk

       - name: Check if revanced-youtube apk is created
         id: check_files
         uses: andstor/file-existence-action@v2
         with:
           files: "revanced-youtube-*-non-root.apk"
           fail: true

       - name: Upload Build Artifact(youtube)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-youtube
           path: |
            revanced-youtube-*-non-root.apk
            vanced-microg.apk

   build-youtube-black:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

       - name: Install Java
         uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
           java-version: '17'

       - name: Update the system
         run: sudo apt install curl ripgrep

       - name: Build youtube
         env:
            KEYSTORE: ${{ secrets.KEYSTORE }}
         run: |
          # curl -OL https://github.com/SubhashBose/revanced-creator/releases/download/keystores/revanced-creator.keystore
          echo "$KEYSTORE" | base64 --decode > revanced-creator.keystore
          export additional_args="--keystore=revanced-creator.keystore -i theme -e hide-watch-in-vr -e hide-video-buttons -e hide-shorts-button -e hide-my-mix -e hide-info-cards -e hide-endscreen-cards -e hide-email-address -e hide-create-button -e hide-captions-button -e hide-breaking-news-shelf -e hide-autoplay-button -e hide-artist-card -e hide-album-cards -e enable-wide-searchbar -e downloads"
          sh -c "$(curl https://raw.githubusercontent.com/SubhashBose/revanced-creator/main/patch.sh)"
          #cat revanced-youtube*.keystore |base64
          curl -OL https://github.com/SubhashBose/revanced-creator/releases/download/youtube/vanced-microg.apk

       - name: Check if revanced-youtube apk is created
         id: check_files
         uses: andstor/file-existence-action@v2
         with:
           files: "revanced-youtube-*-non-root.apk"
           fail: true

       - name: Upload Build Artifact(youtube)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-youtube-black
           path: |
            revanced-youtube-*-non-root.apk
            vanced-microg.apk

   build-yt-music:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

       - name: Install Java
         uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
           java-version: '17'

       - name: Update the system
         run: sudo apt install curl ripgrep

       - name: Build youtube-music
         env:
            KEYSTORE: ${{ secrets.KEYSTORE }}
         run: |
          # curl -OL https://github.com/SubhashBose/revanced-creator/releases/download/keystores/revanced-creator-music.keystore
          echo "$KEYSTORE" | base64 --decode > revanced-creator-music.keystore
          export additional_args="--keystore=revanced-creator-music.keystore"
          export what_to_patch="youtube-music"
          sh -c "$(curl https://raw.githubusercontent.com/SubhashBose/revanced-creator/main/patch.sh)"

       - name: Check if revanced-music apk is created
         id: check_files
         uses: andstor/file-existence-action@v2
         with:
           files: "revanced-music-*-non-root.apk"
           fail: true

       - name: Upload Build Artifact(YouTube-Music)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-music
           path: revanced-music-*-non-root.apk

   build-twitch:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

       - name: Install Java
         uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
           java-version: '17'

       - name: Update the system
         run: sudo apt install curl ripgrep
       - name: Build twitch
         run: |
          export what_to_patch="twitch"
          sh -c "$(curl https://raw.githubusercontent.com/SubhashBose/revanced-creator/main/patch.sh)"

       - name: Check if revanced-twitch apk is created
         id: check_files
         uses: andstor/file-existence-action@v2
         with:
           files: "revanced-twitch-*-non-root.apk"
           fail: true

       - name: Upload Build Artifact(Twitch)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-twitch
           path: revanced-twitch-*-non-root.apk

   build-reddit:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

       - name: Install Java
         uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
           java-version: '17'

       - name: Update the system
         run: sudo apt install curl ripgrep

       - name: Build reddit
         run: |
          # curl -OL https://github.com/SubhashBose/revanced-creator/releases/download/keystores/revanced-creator-reddit.keystore
          # export additional_args="--keystore=revanced-creator-reddit.keystore"
          export what_to_patch="reddit"
          sh -c "$(curl https://raw.githubusercontent.com/SubhashBose/revanced-creator/main/patch.sh)"

       - name: Check if revanced-reddit apk is created
         id: check_files
         uses: andstor/file-existence-action@v2
         with:
           files: "revanced-reddit-*-non-root.apk"
           fail: true

       - name: Upload Build Artifact(Reddit)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-reddit
           path: revanced-reddit-*-non-root.apk

   build-twitter:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

       - name: Install Java
         uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
           java-version: '17'

       - name: Update the system
         run: sudo apt install curl ripgrep
       - name: Build twitter
         run: |
          # curl -OL https://github.com/SubhashBose/revanced-creator/releases/download/keystores/revanced-creator-twitter.keystore
          # export additional_args="--keystore=revanced-creator-twitter.keystore"
          export what_to_patch="twitter"
          sh -c "$(curl https://raw.githubusercontent.com/SubhashBose/revanced-creator/main/patch.sh)"

       - name: Check if revanced-twitter apk is created
         id: check_files
         uses: andstor/file-existence-action@v2
         with:
           files: "revanced-twitter-*-non-root.apk"
           fail: true

       - name: Upload Build Artifact(Twitter)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-twitter
           path: revanced-twitter-*-non-root.apk

   build-tiktok:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

       - name: Install Java
         uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
           java-version: '17'

       - name: Update the system
         run: sudo apt install curl ripgrep
       - name: Build tiktok
         run: |
          export what_to_patch="tiktok"
          sh -c "$(curl https://raw.githubusercontent.com/SubhashBose/revanced-creator/main/patch.sh)"

       - name: Check if revanced-tiktok apk is created
         id: check_files
         uses: andstor/file-existence-action@v2
         with:
           files: "revanced-tiktok-*-non-root.apk"
           fail: true

       - name: Upload Build Artifact(TikTok)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-tiktok
           path: revanced-tiktok-*-non-root.apk

   build-spotify:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

       - name: Install Java
         uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
           java-version: '17'

       - name: Update the system
         run: sudo apt install curl ripgrep
       - name: Build spotify
         run: |
          export what_to_patch="spotify"
          sh -c "$(curl https://raw.githubusercontent.com/SubhashBose/revanced-creator/main/patch.sh)"

       - name: Check if revanced-spotify apk is created
         id: check_files
         uses: andstor/file-existence-action@v2
         with:
           files: "revanced-spotify-*-non-root.apk"
           fail: true

       - name: Upload Build Artifact(Spotify)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-spotify
           path: revanced-spotify-*-non-root.apk
