#This is to be run in target repo

name: Publish Pages

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Download release
        run: |
            wget "https://github.com/${GITHUB_REPOSITORY}/releases/latest/download/pageball.zip"
            unzip -P -P '${{ secrets.PAGEBALL_PASS }}' pageball.zip
            
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
            path: pageball/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
