# RV_APPS_REPO_TOKEN fine grained permission permissions: "Contents" :write 
# RV_APPS_REPO_PATH is USER/REPO

name: Push release pages
on:
#  push:
#    paths:
#      - 'release-versions/*'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v9
        with:
            workflow: ci.yml
      
      - name: Create tag
        id: create_tag
        run: |
          rm -rf ./revanced-youtube
          mv -f ./*/*.apk .
          ls -l
          tag=$(date +%Y-%m-%d_%H%M%S)
          echo "tag=$tag" >> $GITHUB_OUTPUT
      - name: Create zipball
        run: |
            mkdir pageball
            mv *.apk pageball
            cd pageball
            echo "Hello!!" > index.html
            echo "<!DOCTYPE html>
            <html><head><title>List apps</title></head><body>
            <h1>Available APK Files</h1><ul>" > applist.html
            basepath=`echo "${{ secrets.RV_APPS_REPO_PATH }}" | sed 's|/|.github.io/|g'`
            for apk in *.apk; do
                if [[ -f "$apk" ]]; then
                    hash=`echo -n "$apk" | md5sum | awk '{print $1}'`
                    mv "$apk" $hash
                    echo "<li><a href=\"https://${basepath}/$hash\">$apk</a></li>" >> applist.html
                fi
            done
            echo "</ul></body></html>" >> applist.html
            cd ..
            zip -e -P '${{ secrets.PAGEBALL_PASS }}' -r pageball.zip pageball/
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "pageball.zip"
          tag_name: ${{ steps.create_tag.outputs.tag }}
          repository: "${{ secrets.RV_APPS_REPO_PATH }}"
          token: "${{ secrets.RV_APPS_REPO_TOKEN }}"

      - name: Trigger Publish Page remote
        run: |
            curl -H "Authorization: token ${{ secrets.RV_APPS_REPO_TOKEN }}" https://api.github.com/repos/${{ secrets.RV_APPS_REPO_PATH }}/dispatches --request POST --data '{"event_type": "Publish Page Trigger"}' -s
        
