name: Push release
on:
#  push:
#    paths:
#      - 'release-versions/*'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v9
        with:
            workflow: ci.yml
      
      - name: Create tag
        id: create_tag
        run: |
          rm -rf ./revanced-youtube
          mv -f ./*/*.apk .
          ls -l
          tag=$(date +%Y-%m-%d_%H%M%S)
          echo "{tag}={$tag}" >> $GITHUB_OUTPUT
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.apk"
          tag_name: ${{ steps.create_tag.outputs.tag }}
          repository: "sbose-lab/rv-apps"
          token: ${{ secrets.RV_APPS_REPO_TOKEN }}
